---
- hosts: staging_server
  remote_user: zapyle
  vars:
    folder: /home/zapyle/zapyle_staging
    git_repo: git@github.com:Zapyle/zapyle_new.git
    branch: staging
    zapenv: /home/zapyle/zapyle_new/env
  tasks:
  - name: Pulling 'staging' branch from 'zapyle_new' Repository.
    git: 
      repo: "{{git_repo}}" 
      dest: "{{folder}}" 
      version: "{{branch}}"
      force: yes
  - name: Minification of js Files 
    shell: "{{zapenv}}/bin/python manage.py minifyjs --settings=zapyle_new.settings.staging"
    args:
      chdir: "{{folder}}"
  - name: Collecting static files
    shell: "{{zapenv}}/bin/python manage.py collectstatic --noinput --settings=zapyle_new.settings.staging"
    args:
      chdir: "{{folder}}"
  - name: Database makemigrations
    shell: "{{zapenv}}/bin/python manage.py makemigrations --settings=zapyle_new.settings.staging"
    args:
      chdir: "{{folder}}"
  - name: Database migrate
    shell: "{{zapenv}}/bin/python manage.py migrate --settings=zapyle_new.settings.staging"
    args:
      chdir: "{{folder}}"
  - name: Staging server is restarting gunicorn_staging_server
    shell: sudo supervisorctl restart gunicorn_staging_server
    sudo: yes 
  - name: Staging server is restarting zapcelery
    shell: sudo supervisorctl restart zapcelery
    sudo: yes 
  - name: Staging server is restarting zapcelerycam
    shell: sudo supervisorctl restart zapcelerycam
    sudo: yes 
  - name: Staging server is restarting nginx
    service: name=nginx state=restarted
    sudo: yes      
