version: '2'
services:
  db:
    image: postgres
    volumes:
      - .:/code
    ports:
       - "5432"
    environment:
      - Debug=true
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - .:/code
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      - Debug=true
